{% set name = 'python-clingox' %}
{% set dev = not environ.get('BUILD_RELEASE', false) %}
{% set version = environ.get('VERSION_NUMBER') %}
{% set revision = environ.get('GITHUB_SHA', 'wip') %}
{% set build = environ.get('BUILD_NUMBER', "0") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_rev: {{ revision }}
  git_url: https://github.com/potassco/{{ name }}.git

requirements:
  build:
  - setuptools
  - python >=3.5
  - clingo >=5.5.0
  run:
  - python >=3.5
  - clingo >=5.5.0

build:
  number: {{ build }}
  noarch: python
  script: 
    - 'ls -al'
    - 'python setup.py install --single-version-externally-managed --record record.txt'

about:
  home: https://potassco.org/
  license: MIT
  summary: Library with auxilary functions to use along with clingo's python module.
  license_file: LICENSE
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}
